### ISSUE TITLE
12/07/23 - Level 2: Validation Logic (No products Requested)

### ISSUE THREAD

**Issue by u-ways** [u-ways/software-engineering-workexperience#2]
## Background

What if the customer didn't request any products? In this case, we need to reject their request, so we don't waste our time and resources processing it. So if no product is requested, you need to print an error message that says: `No products requested!`

## Requirements 

You need to validate the request data by checking that at least one product is requested.

You should apply your solution inside the `challenge2` function in the `challenge2` file. It takes an object named `Request` as an argument which has the same structure as the one outlined in the requirements.

**Comment by u-ways** [comment]
### Solution:

Since I will be away, here is the solution hidden in the spoiler tag:

<details>
  <summary>:lock: SPOILER ALERT - Only expand this if you want to have a sneak peak for sample solution!</summary>

  ```kotlin
fun challenge2(request: Request) {
    if (request.internet || request.tv) {
        if (request.mobile || request.landline) {
            println("Routing to Broadband & Telecom departments!")
        }
        else {
            println("Routing to Broadband department!")
        }
    }
    else if (request.mobile || request.landline) {
        println("Routing to Telecom department!")
    }

    if (request.internet.not() &&
        request.tv.not() &&
        request.mobile.not() &&
        request.landline.not()
    ) {
        println("No products requested!")
    }
}
  ```
</details>

### What's next?

Once you're satisfied with your solution, head over to [the third challenge](https://github.com/u-ways/software-engineering-work-experience/blob/main/docs/challenge_-_the_firmament_project.md#level-3-validation-logic-mandatory-fields--data-types), you can find the story ticket here: [12/07/23 - Level 3: Validation Logic (Mandatory Fields & Data Types)](https://github.com/u-ways/software-engineering-workexperience/issues/4). Don't forget to add your own dev-analysis so you don't accidentally miss any requirements!

**Comment by leenuja5** [comment]
Co-authored: @miya-rt 

**Dev analysis**

Rejecting a request, if all the different products = "false" 

**All products**
- TV
- Internet
- Landline
- Mobile

**Printing Requirements**
If there are no products requested: `No products requested!`

**Comment by u-ways** [comment]
Nice dev-analysis (all critical points covered!) I've assigned this story to both of you (@miya-rt and @Nuja05) moving this ticket to "In Progress" in our Kanban broad. Goodluck!

### Kotlin's Playground:

If the laptops are giving you issues, you can try solving the challenge using Kotlin's online playground:

[play.kotlinlang.org - Level 2: Validation Logic (No products Requested)](https://pl.kotl.in/MrOn0eWyW)

### We have a Kanban board now!

P.S. This is how [our Kanban board](https://github.com/users/u-ways/projects/3/views/1) looks like right now:

![image](https://github.com/u-ways/software-engineering-workexperience/assets/17771168/6d5edd0f-1590-44f8-aefa-0c53c9f7afec)

**Comment by u-ways** [comment]
Christos told me the Challenge is now complete, well done!
